# Generated by Django 5.0.1 on 2024-02-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data_base64', models.TextField()),
                ('identifier', models.CharField(max_length=36)),
            ],
        ),
    ]
